CFLAGS = -lwiringPi -lpthread -D_GLIBCXX_USE_CXX11_ABI=0

Program: Program.cpp MainBusiness.o MeasureCtrl.o SoundPlay.o volume.o
	g++ $(CFLAGS) Program.cpp MainBusiness.o MeasureCtrl.o SoundPlay.o volume.o -o Program

MainBusiness.o: MainBusiness.cpp
	g++ $(CFLAGS) -c MainBusiness.cpp

MeasureCtrl.o: MeasureCtrl.cpp
	g++ $(CFLAGS) -c MeasureCtrl.cpp

SoundPlay.o: SoundPlay.cpp subprocess.hpp
	g++ $(CFLAGS) -c SoundPlay.cpp

volume.o: volume.cpp
	g++ $(CFLAGS) -c volume.cpp

clean:
	rm *.o Program
